version: '2'

services:
  api:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - eventstore
  eventstore:
    image: adbrowne/eventstore
    ports:
      - "2113:2113"
      - "1113:1113"
